[tool.ruff]
target-version = "py38"

[tool.ruff.lint]
extend-safe-fixes = [
  "ANN",
  "D",
  "TCH",
  "FLY",
  "RUF005",
  "SIM",
  "UP"
]
ignore = [
  "PT",  # CONFIG: Not using pytest
  "D203",  # CONFIG: incompatible with D211
  "D212",  # CONFIG: incompatible with D213
  "ANN101",
  "S101",
  "D100",
  "D101",
  "D102",
  "D103",
  "D105",
  "D107",
  "D205",
  "D401",
  "PTH100",
  "PTH118",
  "PTH120",
  "EM101",
  "RUF012",
  "TRY003",
  "TD",
  "FIX002",
  "SLF001",
  "PLW2901"
]
select = ["ALL"]

[tool.ruff.lint.per-file-ignores]
"docs/conf.py" = ["INP001", "A001"]
"tidy/lib.py" = ["N802", "N816"]
